#!/bin/bash
# Copyright 2018 Bit Factory, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -u
cd $(dirname $0)

ganache-cli --gasLimit 8000000 --port 6545 > /dev/null &
PID=$!

yarn truffle test --network test
EXIT_CODE=$?

kill $PID
exit $EXIT_CODE
